apiVersion: v1
kind: ConfigMap
metadata:
  name: api-configmap
  namespace: tc
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/lanchonete_api?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
  SPRING_DATASOURCE_USERNAME: root
  AWS_REGION: ca-central-1
  AWS_SQS_URL_CHECKOUT: https://sqs.sa-east-1.amazonaws.com/664418989248/checkout-order
  MP_API_URL: https://api.mercadopago.com/instore/orders/qr/seller/collectors/{userId}/pos/{externalPosId}/qrs
  MP_NOTIFICATION_URL: https://webhook.site/8258aa39-758e-4dca-b89f-ce258e6b8919